-- Your SQL goes here
CREATE TABLE post_tags (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, post_id INTEGER REFERENCES posts (post_id) ON DELETE CASCADE NOT NULL, tag_id INTEGER REFERENCES tags (tag_id) ON DELETE CASCADE NOT NULL)
