-- Your SQL goes here
CREATE TABLE posts (id INTEGER PRIMARY KEY UNIQUE NOT NULL, post_id INTEGER UNIQUE NOT NULL, md5 TEXT NOT NULL, rating CHAR REFERENCES ratings (name) ON DELETE CASCADE NOT NULL, width INTEGER, height INTEGER, file_ext TEXT, file_size INTEGER, source TEXT, pixiv_id INTEGER)
